FROM mcr.microsoft.com/playwright/python:v1.57.0-jammy AS build-stage

# install dependencies to run pyinstaller
RUN apt-get update && apt-get install -y \
    bash \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install astral uv
RUN pip install --no-cache-dir --upgrade uv pip

WORKDIR /app

# Copy the application code
# Install dependencies
COPY ./pyproject.toml ./uv.lock ./README.md ./
COPY ./src ./src
RUN uv sync --no-cache-dir

# Build the application binary with pyinstaller
COPY ./build_bin.sh ./
RUN ["chmod", "+x", "./build_bin.sh"]
RUN ./build_bin.sh


FROM mcr.microsoft.com/playwright/python:v1.57.0-jammy

ARG TARGETARCH

# Install necessary packages
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    gnupg \
    lsb-release \
    ca-certificates \
    jq \
    && rm -rf /var/lib/apt/lists/*

# Entrypoint
#COPY docker/entrypoint.sh /entrypoint
#RUN ["chmod", "+x", "/entrypoint"]
#ENTRYPOINT ["/entrypoint"]

# Create a non-root user on debian-based image
RUN groupadd -r app &&  \
    useradd -r -g app app


RUN mkdir -p /app && \
    chown -R app:app /app && \
    chown app:app /usr/local/bin/*

# Set the working directory
WORKDIR /app
# Copy the virtual environment and binary from the build stage
COPY --from=build-stage /app/dist/bin /usr/local/bin

# Environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["webcheckcli", "--help"]
USER app
